services:
  - type: web
    name: rp-campus-care-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    buildFilter:
      paths:
        - frontend/**
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
