services:
  - type: web
    name: rp-campus-care-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      # Root and auth routes
      - type: rewrite
        source: /
        destination: /index.html
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /signup
        destination: /index.html
      - type: rewrite
        source: /signup-profile
        destination: /index.html
      - type: rewrite
        source: /signup-admin
        destination: /index.html
      
      # Dashboard routes
      - type: rewrite
        source: /dashboard
        destination: /index.html
      - type: rewrite
        source: /dashboard/*
        destination: /index.html
      - type: rewrite
        source: /dashboard/**
        destination: /index.html
      
      # Admin routes
      - type: rewrite
        source: /admin
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html
      - type: rewrite
        source: /admin/**
        destination: /index.html
      
      # Report routes
      - type: rewrite
        source: /reports
        destination: /index.html
      - type: rewrite
        source: /reports/*
        destination: /index.html
      - type: rewrite
        source: /reports/**
        destination: /index.html
      - type: rewrite
        source: /report/*
        destination: /index.html
      
      # Task routes
      - type: rewrite
        source: /mytasks
        destination: /index.html
      - type: rewrite
        source: /mytasks/*
        destination: /index.html
      - type: rewrite
        source: /task/*
        destination: /index.html
      - type: rewrite
        source: /history
        destination: /index.html
      - type: rewrite
        source: /history/*
        destination: /index.html
      
      # Chat routes
      - type: rewrite
        source: /chat
        destination: /index.html
      - type: rewrite
        source: /chat/*
        destination: /index.html
      - type: rewrite
        source: /chat/**
        destination: /index.html
      
      # Profile routes
      - type: rewrite
        source: /profile
        destination: /index.html
      - type: rewrite
        source: /profile/*
        destination: /index.html
      
      # Notification routes
      - type: rewrite
        source: /notifications
        destination: /index.html
      - type: rewrite
        source: /notifications/*
        destination: /index.html
      
      # Announcement routes
      - type: rewrite
        source: /announcement-form
        destination: /index.html
      
      # Fallback for any other routes
      - type: rewrite
        source: /*
        destination: /index.html
